# Generated by Django 3.0.4 on 2020-03-04 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerbsRektionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('last_success_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WordSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('last_success_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('german_word', models.CharField(max_length=100)),
                ('article', models.CharField(choices=[('der', 'der'), ('die', 'die'), ('das', 'das')], max_length=3)),
                ('translation', models.CharField(max_length=100)),
                ('part_of_speech', models.CharField(choices=[('verb', 'das Verb'), ('noun', 'das Substantiv'), ('adjective', 'das Adjektiv'), ('conjunction', 'die Konjunktion'), ('other', 'andere')], max_length=30)),
                ('word_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.WordSet')),
            ],
        ),
        migrations.CreateModel(
            name='VerbRektion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField()),
                ('case', models.CharField(choices=[('n', 'Nominativ'), ('g', 'Genitiv'), ('d', 'Dativ'), ('a', 'Akkusativ')], max_length=1)),
                ('translation', models.TextField()),
                ('example', models.TextField()),
                ('verbs_rektion_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.VerbsRektionSet')),
            ],
        ),
    ]
