# Generated by Django 3.0.4 on 2020-03-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='article',
            field=models.CharField(blank=True, choices=[('der', 'der'), ('die', 'die'), ('das', 'das')], max_length=3, null=True),
        ),
    ]
