# Generated by Django 3.0.4 on 2020-03-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20200304_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbsrektionset',
            name='last_success_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wordset',
            name='last_success_rate',
            field=models.IntegerField(default=0),
        ),
    ]
