# Generated by Django 3.0.4 on 2020-03-08 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest_api', '0004_auto_20200307_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateOfLearningSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_obligaory_rounds', models.IntegerField(default=1)),
                ('percent_done', models.IntegerField(default=0)),
                ('corectness_rate', models.IntegerField(default=0)),
                ('learning_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.LearningSet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='verbrektion',
            name='learning_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.LearningSet'),
        ),
        migrations.AlterField(
            model_name='word',
            name='learning_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.LearningSet'),
        ),
        migrations.CreateModel(
            name='StateOfVerbRektion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('number_of_correct_answers', models.IntegerField(default=0)),
                ('state_of_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.StateOfLearningSet')),
                ('verb_rektion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.VerbRektion')),
            ],
        ),
        migrations.CreateModel(
            name='state_of_word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('number_of_correct_answers', models.IntegerField(default=0)),
                ('state_of_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.StateOfLearningSet')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Word')),
            ],
        ),
    ]
