# Generated by Django 3.0.4 on 2020-03-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_auto_20200308_2139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='state_of_word',
            new_name='StateOfWord',
        ),
    ]
