# Generated by Django 3.0.4 on 2020-03-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_auto_20200308_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='verbrektion',
            name='preposition',
            field=models.TextField(default=''),
        ),
    ]
