# Generated by Django 3.0.4 on 2020-03-15 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_verbrektion_preposition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stateoflearningset',
            old_name='user',
            new_name='owner',
        ),
    ]
