# Generated by Django 3.0.4 on 2020-03-15 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_auto_20200315_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateofverbrektion',
            name='state_of_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sets_states', to='rest_api.StateOfLearningSet'),
        ),
    ]
