version: '3'

services:
  db:
    image: postgres:11
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=testodb
      - POSTGRES_USER=testo
      - POSTGRES_PASSWORD=W4lepsze
    volumes:
      - data:/var/lib/postgresql/data/
  web:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: python3 backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  front:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - './frontend/:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
    depends_on:
      - web
volumes:
  data: